# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: King Sidharth
permalink: /:categories/:title/
url: https://www.kingsidharth.com
author:
  name: King Sidharth
  email: king@kingsidharth.com

source: app
destination: public

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "speaking"
      type: "posts"
    values:
      layout: "talk"
      categories: "speaking"
    output: true
  -
    scope:
      path: "work"
      type: "project"
    values:
      layout: "project"
      categories: "projects"
    output: true


include: ['.htaccess']
exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', '.git', 'Readme.md', '.sass-cache', 'webpack', 'index.js', 'js_modules']

encoding: "utf-8"

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: false

# Markdown library
# markdown: maruku
#   use_tex:    false
#   use_divs:   false
#   png_engine: blahtex
#   png_dir:    images/latex
#   png_url:    /images/latex
